name: "Run unit tests"

on:
  workflow_call:
    inputs:
      os:
        description: "OS image(s)"
        default: '["ubuntu-24.04" ]'
      civicrm:
        description: "CiviCRM Core Version(s)"
        default: '["5.69"]'
      mysql:
        description: "MySQL version(s)"
        default: '["8.0"]'
      php:
        description: "PHP version(s)"
        default: '["8.1"]'

jobs:
  install-civicrm:
    strategy:
      matrix:
        os: ${{ fromJSON(github.event.inputs.products) }}
        civicrm: ${{ fromJSON(github.event.inputs.civicrm) }}
        mysql: ${{ fromJSON(github.event.inputs.mysql) }}
        php: ${{ fromJSON(github.event.inputs.php) }}
    runs-on: "${{ matrix.os }}"

    services:
      mysql:
        image: "mysql:${{ matrix.mysql }}"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval="10s"
          --health-timeout="5s"
          --health-retries="3"

    steps:
      - id: "install-deps"
        name: "Install dependencies"
        run: |
          sudo apt install lynx
          sudo rm /etc/alternatives/php
          sudo ln -s "/usr/bin/php${{ matrix.php }}" "/etc/alternatives/php"

      - id: "install-buildkit"
        name: "Install CiviCRM buildkit"
        run: |
          curl -LOs "https://civicrm.org/get-buildkit.sh"
          chmod +x "./get-buildkit.sh"
          ./get-buildkit.sh --full --dir "/home/runner/buildkit"

      - id: "amp-config"
        name: "Configure amp"
        run: |
          PATH="/home/runner/buildkit/bin:$PATH"
          amp config:set --db_type="mysql_dsn"
          amp config:set --hosts_type="file"
          amp config:set --httpd_type="apache24"
          amp config:set --httpd_restart_command="sudo /usr/sbin/apachectl graceful"
          amp config:set --mysql_dsn="mysql://root@localhost:3306"
          amp config:set --perm_type="worldWritable"
          sudo chmod 666 "/etc/apache2/apache2.conf"
          echo "IncludeOptional /home/runner/.amp/apache.d/*.conf" >> "/etc/apache2/apache2.conf"
          amp test

      - id: "build-instance"
        name: "Build a CiviCRM instance"
        run: |
          /home/runner/buildkit/bin/civibuild create "civi" \
            --civi-ver "${{ matrix.civicrm }}" \
            --title "CiviCRM (${{ matrix.civicrm }})" \
            --type "drupal-clean" \
            --url "http://civi.test:8080"

      - id: "clone-mailutils-repo"
        name: "Clone the mailutils repository"
        uses: "actions/checkout@v3"
        with:
          # repository: "greenpeace-cee/mailutils"
          ref: "${{ github.ref_name }}"
          # token: "${{ secrets.ACCESS_TOKEN }}"
          path: "mailutils"

      - id: "install-extension"
        name: "Install the mailutils extension"
        env:
          EXT_DIR: "/home/runner/buildkit/build/civi/web/sites/default/files/civicrm/ext"
        run: |
          cp -R "$GITHUB_WORKSPACE/mailutils" "$EXT_DIR/mailutils"
          git clone https://github.com/greenpeace-cee/at.greenpeace.casetools.git "$EXT_DIR/at.greenpeace.casetools"
          cd "/home/runner/buildkit/build/civi"
          /home/runner/buildkit/bin/cv en "mailutils"

      - id: "run-unit-tests"
        name: "Run unit tests"
        env:
          EXT_DIR: "/home/runner/buildkit/build/civi/web/sites/default/files/civicrm/ext"
        run: |
          PATH="/home/runner/buildkit/bin:$PATH"
          cd "$EXT_DIR/mailutils"
          CIVICRM_UF="UnitTests" phpunit9
